ark:
  container_name: ark_server
  image: mdestombes/ark_server:v1.1
  environment:
    - SESSIONNAME="Ark Docker"
    - SERVERMAP="TheIsland"
    - SERVERPASSWORD="ServerPassword" 
    - ADMINPASSWORD="AdminPassword"
    - BACKUPONSTART=0
    - UPDATEONSTART=0
    - TZ=Europe/Paris
  volumes:
    - /my/path/to/ark:/ark
  ports:
   - 7778:7778/udp
   - 7778:7778
   - 27015:27015/udp
   - 27015:27015
   - 32330:32330
